#! /bin/bash

if [ -z "$POTCARDIR" ]
then
    echo "\$POTCARDIR is not set"
    exit 1
fi

potcar_dir=$POTCARDIR

for potcar in $@
do
  if [ ! -e "$potcar_dir/$potcar" ]
  then
    echo -e "\n\"$potcar\" not found in $potcar_dir" 1>&2
    echo -e "\nAvailable pseudopotentials:\n" 1>&2
    get_potcar_list.py -l 1>&2
    # Modify this to return useful suggestions; i.e. mkpotcar Li_foo suggests Li, Li_sv, Li_sv2, etc.
    echo -e "" 1>&2
    exit 1
  fi
done

for potcar in $@
do
  cat $potcar_dir/$potcar/POTCAR
done
